package tw.edu.sinica.iis.ants.db.antrip;
// Generated Dec 17, 2012 4:07:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * TripSharingId generated by hbm2java
 */
public class TripSharingId implements java.io.Serializable {

	private int userId;
	private int userIdFriend;
	private int tripId;

	public TripSharingId() {
	}

	public TripSharingId(int userId, int userIdFriend, int tripId) {
		this.userId = userId;
		this.userIdFriend = userIdFriend;
		this.tripId = tripId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getUserIdFriend() {
		return this.userIdFriend;
	}

	public void setUserIdFriend(int userIdFriend) {
		this.userIdFriend = userIdFriend;
	}

	public int getTripId() {
		return this.tripId;
	}

	public void setTripId(int tripId) {
		this.tripId = tripId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TripSharingId))
			return false;
		TripSharingId castOther = (TripSharingId) other;

		return (this.getUserId() == castOther.getUserId())
				&& (this.getUserIdFriend() == castOther.getUserIdFriend())
				&& (this.getTripId() == castOther.getTripId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserId();
		result = 37 * result + this.getUserIdFriend();
		result = 37 * result + this.getTripId();
		return result;
	}

}
