package tw.edu.sinica.iis.ants.db_pojo.linkus;
import java.sql.Timestamp;
/**
 * LinkiusUserInfo generated by hbm2java
 */
public class LinkusInteraction implements java.io.Serializable {
	

	private String fbId;
	private String lng;
	private String lat;
	private String candidateId;
	private int status;
	private Timestamp time;

		
		public LinkusInteraction() {
		}
			
		public LinkusInteraction(String fbId,String lng,String lat, String candidateId,
				int status) {
			this.fbId = fbId;
			this.lng = lng;
			this.lat = lat;
			this.candidateId= candidateId;
			this.status = status;
		}

		public String getFbId() {
			return fbId;
		}

		public void setFbId(String fbId) {
			this.fbId = fbId;
		}

		public String getLng() {
			return lng;
		}

		public void setLng(String lng) {
			this.lng = lng;
		}

		public String getLat() {
			return lat;
		}

		public void setLat(String lat) {
			this.lat = lat;
		}

		public String getCandidateId() {
			return candidateId;
		}

		public void setCandidateId(String candidateId) {
			this.candidateId = candidateId;
		}

		public int getStatus() {
			return status;
		}

		public void setStatus(int status) {
			this.status = status;
		}

		public Timestamp getTime() {
			return time;
		}

		public void setTime(Timestamp time) {
			this.time = time;
		}

	
		

	
	
		
		
		
	}

