package tw.edu.sinica.iis.ants.db_pojo.linkus;
import java.sql.Timestamp;
/**
 * LinkiusUserInfo generated by hbm2java
 */
public class LinkusLocations implements java.io.Serializable {
	

	private String fbId;
	private String locationId;
	private String locationName;
	private String lng;
	private String lat;

		
		public LinkusLocations() {
		}
			
		public LinkusLocations(String fbId,String locationId,String locationName,String lng,String lat) {
			this.fbId = fbId;
			this.locationId = locationId;
			this.locationName= locationName;
			this.lng= lng;
			this.lat= lat;
		}

		public String getFbId() {
			return fbId;
		}

		public void setFbId(String fbId) {
			this.fbId = fbId;
		}

		public String getLocationId() {
			return locationId;
		}

		public void setLocationId(String locationId) {
			this.locationId = locationId;
		}

		public String getLocationName() {
			return locationName;
		}

		public void setLocationName(String locationName) {
			this.locationName = locationName;
		}

		public String getLng() {
			return lng;
		}

		public void setLng(String lng) {
			this.lng = lng;
		}

		public String getLat() {
			return lat;
		}

		public void setLat(String lat) {
			this.lat = lat;
		}

		

		
	
		
		
		
	}

