package tw.edu.sinica.iis.ants.db_pojo.linkus;
import java.sql.Timestamp;
/**
 * LinkiusUserInfo generated by hbm2java
 */
public class LinkusPhotos implements java.io.Serializable {
	

	private String fbId;
	private String photoId;
	private String url;
		
		public LinkusPhotos() {
		}
			
		public LinkusPhotos(String fbId,String photoId,String url) {
			this.fbId = fbId;
			this.photoId = photoId;
			this.url= url;
		}

		public String getFbId() {
			return fbId;
		}

		public void setFbId(String fbId) {
			this.fbId = fbId;
		}

		public String getPhotoId() {
			return photoId;
		}

		public void setPhotoId(String photoId) {
			this.photoId = photoId;
		}

		public String getUrl() {
			return url;
		}

		public void setUrl(String url) {
			this.url = url;
		}

		
	
		
		
		
	}

