package tw.edu.sinica.iis.ants.db_pojo.linkus;
import java.sql.Timestamp;
/**
 * LinkiusUserInfo generated by hbm2java
 */
public class LinkusUserInfo implements java.io.Serializable {
	

		private String fbId;
		private String fbToken;
		private String education;
		private String lng;
		private String lat;
		private Timestamp time;
		private String name;
		private String bday;
		private String gender;
		private String workExp;
		
		public LinkusUserInfo() {
		}
			
		public LinkusUserInfo(String fbId,String fbToken,String education, String lng,
				String lat) {
			this.fbId = fbId;
			this.fbToken = fbToken;
			this.lng = lng;
			this.lat = lat;
			this.education= education;
		}
		
		public String getFbId() {
			return fbId;
		}

		public void setFbId(String fbId) {
			this.fbId = fbId;
		}

		public String getFbToken() {
			return fbToken;
		}

		public void setFbToken(String fbToken) {
			this.fbToken = fbToken;
		}

		public String getEducation() {
			return education;
		}

		public void setEducation(String education) {
			this.education = education;
		}

		public String getLng() {
			return lng;
		}

		public void setLng(String lng) {
			this.lng = lng;
		}

		public String getLat() {
			return lat;
		}

		public void setLat(String lat) {
			this.lat = lat;
		}

		public Timestamp getTime() {
			return time;
		}

		public void setTime(Timestamp time) {
			this.time = time;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public String getBday() {
			return bday;
		}

		public void setBday(String bday) {
			this.bday = bday;
		}

		public String getGender() {
			return gender;
		}

		public void setGender(String gender) {
			this.gender = gender;
		}

		public String getWorkExp() {
			return workExp;
		}

		public void setWorkExp(String workExp) {
			this.workExp = workExp;
		}
		
		
		
	}

