package tw.edu.sinica.iis.ants.db_pojo.linkus;
import java.sql.Timestamp;
/**
 * LinkiusUserInfo generated by hbm2java
 */
public class LinkusUser implements java.io.Serializable {
	

	private String fbId;
	private String lng;
	private String lat;
    private Timestamp time;	
	private String preference;
	private String radius;

		
		public LinkusUser() {
		}
			
		public LinkusUser(String fbId,String lng,String lat, String preference,
				String radius) {
			this.fbId = fbId;
			this.lng = lng;
			this.lat = lat;
			this.preference= preference;
			this.radius = radius;
		}

		public String getFbId() {
			return fbId;
		}

		public void setFbId(String fbId) {
			this.fbId = fbId;
		}

		public String getLng() {
			return lng;
		}

		public void setLng(String lng) {
			this.lng = lng;
		}

		public String getLat() {
			return lat;
		}

		public void setLat(String lat) {
			this.lat = lat;
		}

		public Timestamp getTime() {
			return time;
		}

		public void setTime(Timestamp time) {
			this.time = time;
		}

		public String getPreference() {
			return preference;
		}

		public void setPreference(String preference) {
			this.preference = preference;
		}

		public String getRadius() {
			return radius;
		}

		public void setRadius(String radius) {
			this.radius = radius;
		}

	
	
		
		
		
	}

