package tw.edu.sinica.iis.ants.db_pojo.linkus;

// Generated Jul 18, 2012 7:38:37 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo {
	
	private String fbId;
	private String fbToken;
	private String education;
	private String lon;
	private String lat;
	private Timestamp time;
	private String name;
	private String bday;
	private String gender;
	private String workExp;
	
	public String getFbId() {
		return fbId;
	}

	public void setFbId(String fbId) {
		this.fbId = fbId;
	}

	public String getFbToken() {
		return fbToken;
	}

	public void setFbToken(String fbToken) {
		this.fbToken = fbToken;
	}

	public String getEducation() {
		return education;
	}

	public void setEducation(String education) {
		this.education = education;
	}

	public String getLon() {
		return lon;
	}

	public void setLon(String lon) {
		this.lon = lon;
	}

	public String getLat() {
		return lat;
	}

	public void setLat(String lat) {
		this.lat = lat;
	}

	public Timestamp getTime() {
		return time;
	}

	public void setTime(Timestamp time) {
		this.time = time;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getBday() {
		return bday;
	}

	public void setBday(String bday) {
		this.bday = bday;
	}

	public String getGender() {
		return gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getWorkExp() {
		return workExp;
	}

	public void setWorkExp(String workExp) {
		this.workExp = workExp;
	}
	
	public UserInfo() {
	}
		
	public String getfbId() {
		return this.fbId;
	}

	public String getfbToken() {
		return this.fbToken;
	}
	public String getname() {
		return this.name;
	}
	public String geteducation() {
		return this.education;
	}
	public String getbday() {
		return this.bday;
	}
	public String getgender() {
		return this.gender;
	}
	public String getworkExp() {
		return this.workExp;
	}
	public String getlon() {
		return this.lon;
	}
	public String getlat() {
		return this.lat;
	}
	public Timestamp gettime() {
		return this.time;
	}

}