package tw.edu.sinica.iis.ants.db_pojo.linkus;

// Generated Jul 18, 2012 7:38:37 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private String fbId;
	private String fbToken;
	private String education;
	private String lon;
	private String lat;
	private Timestamp time;
	private String name;
	private String bday;
	private String gender;
	private String workExp;

	
	
	public UserInfo() {
	}

	public UserInfo(String fbId, String fbToken, String education, String lon, String lat, Timestamp time) {
		this.fbId = fbId;
		this.fbToken = fbToken;
		this.education = education;
		this.lon = lon;
		this.lat = lat;
		this.time = time;
	}

	public UserInfo(String fbId, String fbToken, String education, String lon, String lat, Timestamp time,
			        String name,String bday,String gender, String workExp ) {
		this.fbId = fbId;
		this.fbToken = fbToken;
		this.education = education;
		this.lon = lon;
		this.lat = lat;
		this.time = time;
		this.name = name;
		this.bday = bday;
		this.gender = gender;
		this.workExp = workExp;
	
	}


		
	public String getfbId() {
		return this.fbId;
	}

	public String getfbToken() {
		return this.fbToken;
	}
	public String getname() {
		return this.name;
	}
	public String geteducation() {
		return this.education;
	}
	public String getbday() {
		return this.bday;
	}
	public String getgender() {
		return this.gender;
	}
	public String getworkExp() {
		return this.workExp;
	}
	public String getlon() {
		return this.lon;
	}
	public String getlat() {
		return this.lat;
	}
	public Timestamp gettime() {
		return this.time;
	}

}