package tw.edu.sinica.iis.ants.db_pojo.linkus;

// Generated Jul 18, 2012 7:38:37 PM by Hibernate Tools 3.4.0.CR1

import java.sql.Timestamp;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo implements java.io.Serializable {

	private String fbId;
	private String fbToken;
	private String name;
	private String education;
	private String bday;
	private String gender;
	private String workExp;
	private double lon;
	private double lat;
	private Timestamp time;
	


	
	
	public UserInfo() {
	}

	public UserInfo(int UserId, short updateStatus) {
		this.UserId = UserId;
		this.updateStatus = updateStatus;
	}

	public UserInfo(int UserId, Timestamp startTime,
			Timestamp endTime, Integer tripLength, Integer numOfPts,
			String stAddrPrt1, String stAddrPrt2, String stAddrPrt3,
			String stAddrPrt4, String stAddrPrt5, String etAddrPrt1,
			String etAddrPrt2, String etAddrPrt3, String etAddrPrt4,
			String etAddrPrt5, short updateStatus) {
		this.UserId = UserId;
		this.startTime = startTime;
		this.endTime = endTime;
		this.tripLength = tripLength;
		this.numOfPts = numOfPts;
		this.stAddrPrt1 = stAddrPrt1;
		this.stAddrPrt2 = stAddrPrt2;
		this.stAddrPrt3 = stAddrPrt3;
		this.stAddrPrt4 = stAddrPrt4;
		this.stAddrPrt5 = stAddrPrt5;
		this.etAddrPrt1 = etAddrPrt1;
		this.etAddrPrt2 = etAddrPrt2;
		this.etAddrPrt3 = etAddrPrt3;
		this.etAddrPrt4 = etAddrPrt4;
		this.etAddrPrt5 = etAddrPrt5;
		this.updateStatus = updateStatus;
	}


		
	public String getfbId() {
		return this.fbId;
	}

	public String getfbToken() {
		return this.fbToken;
	}
	public String getname() {
		return this.name;
	}
	public String geteducation() {
		return this.education;
	}
	public String getbday() {
		return this.bday;
	}
	public String getgender() {
		return this.gender;
	}
	public String getworkExp() {
		return this.workExp;
	}
	public double getlon() {
		return this.lon;
	}
	public double getlat() {
		return this.lat;
	}
	public Timestamp gettime() {
		return this.time;
	}

	