package tw.edu.sinica.iis.ants.db_pojo.common;

// Generated Jul 16, 2012 8:52:03 PM by Hibernate Tools 3.4.0.CR1

import com.vividsolutions.jts.geom.Geometry;

/**
 * PointBinaryData generated by hbm2java
 */
public class PointBinaryData implements java.io.Serializable {

	private long pointId;
	private Geometry postgisPoint;

	public PointBinaryData() {
	}

	public PointBinaryData(long pointId) {
		this.pointId = pointId;
	}

	public PointBinaryData(long pointId, Geometry postgisPoint) {
		this.pointId = pointId;
		this.postgisPoint = postgisPoint;
	}

	public long getPointId() {
		return this.pointId;
	}

	public void setPointId(long pointId) {
		this.pointId = pointId;
	}

	public Geometry getPostgisPoint() {
		return this.postgisPoint;
	}

	public void setPostgisPoint(Geometry postgisPoint) {
		this.postgisPoint = postgisPoint;
	}

}
