package tw.edu.sinica.iis.ants.db_pojo.common;

// Generated Jul 16, 2012 8:53:23 PM by Hibernate Tools 3.4.0.CR1

/**
 * UserSpecified generated by hbm2java
 */
public class UserSpecified implements java.io.Serializable {

	private long pointId;
	private Short mood;
	private Short transportationType;

	public UserSpecified() {
	}

	public UserSpecified(long pointId) {
		this.pointId = pointId;
	}

	public UserSpecified(long pointId, Short mood, Short transportationType) {
		this.pointId = pointId;
		this.mood = mood;
		this.transportationType = transportationType;
	}

	public long getPointId() {
		return this.pointId;
	}

	public void setPointId(long pointId) {
		this.pointId = pointId;
	}

	public Short getMood() {
		return this.mood;
	}

	public void setMood(Short mood) {
		this.mood = mood;
	}

	public Short getTransportationType() {
		return this.transportationType;
	}

	public void setTransportationType(Short transportationType) {
		this.transportationType = transportationType;
	}

}
