package tw.edu.sinica.iis.ants.db_pojo.antrip;
// Generated Dec 17, 2012 4:07:38 PM by Hibernate Tools 3.4.0.CR1

/**
 * TripSharing generated by hbm2java
 */
public class TripSharing implements java.io.Serializable {

	private TripSharingId id;

	public TripSharing() {
	}

	public TripSharing(TripSharingId id) {
		this.id = id;
	}

	public TripSharingId getId() {
		return this.id;
	}

	public void setId(TripSharingId id) {
		this.id = id;
	}

}
