package tw.edu.sinica.iis.ants.db.common;

// Generated Jul 16, 2012 8:52:19 PM by Hibernate Tools 3.4.0.CR1

/**
 * PointDeviceData generated by hbm2java
 */
public class PointDeviceData implements java.io.Serializable {

	private long pointId;
	private String gsmInfo;
	private String wifiInfo;
	private Short application;
	private String deviceInfo;
	private String battery;
	private String imei;
	private String extra;

	public PointDeviceData() {
	}

	public PointDeviceData(long pointId) {
		this.pointId = pointId;
	}

	public PointDeviceData(long pointId, String gsmInfo, String wifiInfo,
			Short application, String deviceInfo, String battery, String imei,
			String extra) {
		this.pointId = pointId;
		this.gsmInfo = gsmInfo;
		this.wifiInfo = wifiInfo;
		this.application = application;
		this.deviceInfo = deviceInfo;
		this.battery = battery;
		this.imei = imei;
		this.extra = extra;
	}

	public long getPointId() {
		return this.pointId;
	}

	public void setPointId(long pointId) {
		this.pointId = pointId;
	}

	public String getGsmInfo() {
		return this.gsmInfo;
	}

	public void setGsmInfo(String gsmInfo) {
		this.gsmInfo = gsmInfo;
	}

	public String getWifiInfo() {
		return this.wifiInfo;
	}

	public void setWifiInfo(String wifiInfo) {
		this.wifiInfo = wifiInfo;
	}

	public Short getApplication() {
		return this.application;
	}

	public void setApplication(Short application) {
		this.application = application;
	}

	public String getDeviceInfo() {
		return this.deviceInfo;
	}

	public void setDeviceInfo(String deviceInfo) {
		this.deviceInfo = deviceInfo;
	}

	public String getBattery() {
		return this.battery;
	}

	public void setBattery(String battery) {
		this.battery = battery;
	}

	public String getImei() {
		return this.imei;
	}

	public void setImei(String imei) {
		this.imei = imei;
	}

	public String getExtra() {
		return this.extra;
	}

	public void setExtra(String extra) {
		this.extra = extra;
	}

}
