#!/bin/bash
# Program:
# 	Using CheckServerStatus to detect Mule Server services.
# History:
# 2012/12/28	Yu-Hsiang Huang	First release
PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:~/bin
export PATH

testing=$(curl -1 -m 5 --insecure --write-out %{http_code} --silent --output /deull https://localhost:8080/CheckServerStatus)
if [ "$testing" != "200" ]; then
	/etc/init.d/plash restart
	FILEDATE=`date +%F`
	LOGFILE=/opt/plash/logs/Restart.$FILEDATE.log
	if [ ! -f $LOGFILE ]; then
		touch $LOGFILE
	fi
	nowTIME=`date`
	echo "Plash Mule ESB was restarted at $nowTIME."  >> $LOGFILE
else
	FILEDATE=`date +%F`
        LOGFILE=/opt/plash/logs/Running.$FILEDATE.log
        if [ ! -f $LOGFILE ]; then
                touch $LOGFILE
        fi
	nowTIME=`date`
	echo "Plash Mule ESB is running at $nowTIME."	>> $LOGFILE
	echo "Plash Mule ESB is running at $nowTIME."
fi
