#!/bin/bash

# Set JDK related environment
JAVA_HOME=/usr/lib/jvm/java-6-sun
PATH=$PATH:$JAVA_HOME/bin

# Set Mule related environment
MULE_HOME=/opt/plash
MULE_LIB=/opt/plash/PLASH_Platform_Test/conf
PATH=$PATH:$MULE_HOME/bin

# Export environment variables
export JAVA_HOME MULE_HOME MULE_LIB PATH

# Invoke Mule
# ./bin/mule -config PLASH_Platform_Test/conf/plash.xml, PLASH_Platform_Test/conf/spring_plash.xml
/etc/init.d/activemq restart
$MULE_HOME/bin/mule $1 -config /opt/plash/PLASH_Platform_Test/conf/PLASH_model_config_console.xml
